"""empty message

Revision ID: 35473c0ae0b0
Revises: 64903f2b4f3c
Create Date: 2026-01-14 15:02:42.269067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35473c0ae0b0'
down_revision = '64903f2b4f3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
