"""Initial migration

Revision ID: 56b127ff85d1
Revises: 
Create Date: 2026-01-07 22:18:03.660276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56b127ff85d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_items_store_id', 'stores', ['store_id'], ['id'])
        batch_op.create_unique_constraint('uq_items_name', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_items_store_id', type_='foreignkey')
        batch_op.drop_constraint('uq_items_name', type_='unique')
        batch_op.drop_column('store_id')

    # ### end Alembic commands ###
